[workspace]
members = [
  "contracts/*",
  "daemon",
  "sdk",
  "server",
  "store",
]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
