# NOTE:
# 1. We only want to make sure that the contract compiles; we don't need to
#    produce release builds. Therefore we don't include the `--release` flag.
# 2. We only want to compile contracts to the wasm target, not cwd and others.
#    Use the `--exclude` flag to exclude them.
# 3. Since we exlude cw-store, we can use the stable toolchain.
on: push
name: CosmWasm
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal
      - name: Build contracts
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: >
            --locked --lib --target wasm32-unknown-unknown --workspace
            --exclude cwd
            --exclude cw-server
            --exclude cw-state-machine
            --exclude cw-store
        env:
          RUST_BACKTRACE: 1
